# Port your server runs on
server.port=8080

# Where is the database
spring.datasource.url=jdbc:postgresql://localhost:5432/financedb

# Database credentials
spring.datasource.username=nayan
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Tell Hibernate to auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console so you can see what's happening
spring.jpa.show-sql=true

# Tell hibernate which database dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Suppress a warning about lazy loading
spring.jpa.open-in-view=false