# Port your server runs on
server.port=8080

# Where is the database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financedb}
spring.datasource.username=${DB_USERNAME:nayan}
spring.datasource.password=${DB_PASSWORD:password}
application.security.jwt.secret=${JWT_SECRET}

# Tell Hibernate to auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console so you can see what's happening
spring.jpa.show-sql=true

# Tell hibernate which database dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Suppress a warning about lazy loading
spring.jpa.open-in-view=false

application.security.jwt.expiration=86400000